services:
  llama-chatbot:
    build: .
    ports:
      - "8501:8501"    # Streamlit
      - "11435:11434"  # Ollama remapped port
    volumes:
      - ./vector_db:/app/vector_db        # Persist vector database
      - ollama_data:/root/.ollama         # Persist Ollama models
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - OLLAMA_HOST=0.0.0.0:11434
    depends_on:
      - postgres
    networks:
      - app-network
 
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: backup_m
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PASSWORD: '1234'
    ports:
      - "5432:5432"  # Remapped to avoid host conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
 
volumes:
  ollama_data:
  postgres_data:
 
networks:
  app-network:
    driver: bridge